# Factors

In [1]:
import pandas as pd
from scipy.optimize import minimize
import statsmodels.api as sm

#%pylab inline

c:\users\samth\miniconda3\envs\econ\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [2]:
# pd.read_csv("C:/Data/Thesis/Factors.csv").set_index("date")

F = pd.read_stata("C:/Data/Thesis/Factors.dta").set_index("date")

In [3]:
ff2015 = ["rm", "smb", "hmlo", "rmw", "cma"]
ff2016 = ["rm", "smb", "hml", "RMWc", "cma"]
ff2016b = ["rm", "smb", "hml", "RMWr", "cma"]
b2016 = ["rm", "smb", "HMLm", "wml", "RMWc"]

## Summary Statistics

### French Dartmouth Website

In [ ]:
x = ["SMB", "smb", "HML", "hml", "RMW", "rmw", "CMA", "cma", "WML", "wml"]
tbl = pd.concat({"Mean":  F[x].mean(),
                 "Stdev": F[x].std(),
                 "N":     F[x].count()}, axis="columns")

tbl["t-stat"] = tbl["Mean"] / (tbl["Stdev"] / pd.np.sqrt(tbl["N"]))
round(tbl.drop("N", axis=1).transpose(), 2)

In [ ]:
x = ["HMLs", "HMLb", "RMWs", "RMWb", "CMAs", "CMAb", "WMLs", "WMLb"]
tbl = pd.concat({"Mean":  F[x].mean(),
                 "Stdev": F[x].std(),
                 "N":     F[x].count()}, axis="columns")

tbl["t-stat"] = tbl["Mean"] / (tbl["Stdev"] / pd.np.sqrt(tbl["N"]))
round(tbl.drop("N", axis=1).transpose(), 2)

### Fama French (2016) _Choosing Factors_

In [ ]:
x = ["HML", "HMLs", "HMLb", "RMWr", "RMWrs", "RMWrb",
     "RMWc", "RMWcs", "RMWcb", "CMA", "CMAs", "CMAb"]
tbl = pd.concat({"Mean":  F[:"2015"][x].mean(),
                 "Stdev": F[:"2015"][x].std(),
                 "N":     F[:"2015"][x].count()}, axis="columns")

tbl["t-stat"] = tbl["Mean"] / (tbl["Stdev"] / pd.np.sqrt(tbl["N"]))
round(tbl.drop("N", axis=1).transpose(), 2)

### Table 1

In [ ]:
x = ["rm", "smb", "hml", "HMLm", "RMWc", "cma", "wml"]
tbl = pd.concat({"Mean":  F[x].mean(),
                 "Stdev": F[x].std(),
                 "N":     F[x].count()}, axis="columns")

tbl["t-stat"] = tbl["Mean"] / (tbl["Stdev"] / pd.np.sqrt(tbl["N"]))
tbl["Sh"] = tbl["Mean"] / tbl["Stdev"]
tbl["Sh2"] = tbl["Sh"]**2
round(tbl.drop("N", axis=1).transpose(), 2)

### Value

In [ ]:
x = ["HMLs", "HMLb", "HML", "HMLcs", "HMLcb", "HMLc",
     "HMLms", "HMLmb", "HMLm"]
tbl = pd.concat({"Mean":  F[x].mean(),
                 "Stdev": F[x].std(),
                 "N":     F[x].count()}, axis="columns")

tbl["t-stat"] = tbl["Mean"] / (tbl["Stdev"] / pd.np.sqrt(tbl["N"]))
round(tbl.drop("N", axis=1).transpose(), 2)

### Profit

In [ ]:
x = ["RMWs", "RMWb", "RMW", "RMWrs", "RMWrb", "RMWr",
     "RMWgs", "RMWgb", "RMWg", "RMWcs", "RMWcb", "RMWc"]
tbl = pd.concat({"Mean":  F[x].mean(),
                 "Stdev": F[x].std(),
                 "N":     F[x].count()}, axis="columns")

tbl["t-stat"] = tbl["Mean"] / (tbl["Stdev"] / pd.np.sqrt(tbl["N"]))
round(tbl.drop("N", axis=1).transpose(), 2)

## Sharpe Ratio

We are inverting a matrix - check the condition number.

In [4]:
r = F[:"2015"][ff2016].mean()
Vf = F[:"2015"][ff2016].cov()

r.dot(pd.np.linalg.pinv(Vf)).dot(r)

0.24691783857468111

In [5]:
r = F[:"2015"][ff2016].mean().as_matrix()
Vf = F[:"2015"][ff2016].cov().as_matrix()

r @ pd.np.linalg.pinv(Vf) @ r

0.24691783857468111

In [7]:
r = F[:"2015"][ff2016b].mean()
Vf = F[:"2015"][ff2016b].cov()

r.dot(pd.np.linalg.pinv(Vf)).dot(r)

0.18153059101603303

In [8]:
r = F[:"2015"][b2016].mean()
Vf = F[:"2015"][b2016].cov()

r.dot(pd.np.linalg.pinv(Vf)).dot(r)

0.35805656899647442

In [9]:
r = F[:"2016"][b2016].mean()
Vf = F[:"2016"][b2016].cov()

r.dot(pd.np.linalg.pinv(Vf)).dot(r)

0.36077403320733548

In [10]:
r = F[:"2016"][b2016+["STR",]].mean()
Vf = F[:"2016"][b2016+["STR",]].cov()

r.dot(pd.np.linalg.pinv(Vf)).dot(r)

0.3756723309552103

In [ ]:
r = F["2000":"2016"][ff2016].mean()
Vf = F["2000":"2016"][ff2016].cov()

r.dot(pd.np.linalg.pinv(Vf)).dot(r)

In [ ]:
r = F["2000":"2016"][b2016].mean()
Vf = F["2000":"2016"][b2016].cov()

r.dot(pd.np.linalg.pinv(Vf)).dot(r)

In [ ]:
r = F["1963":"1999"][ff2016].mean()
Vf = F["1963":"1999"][ff2016].cov()

r.dot(pd.np.linalg.pinv(Vf)).dot(r)

In [ ]:
r = F["1963":"1999"][b2016].mean()
Vf = F["1963":"1999"][b2016].cov()

r.dot(pd.np.linalg.pinv(Vf)).dot(r)

## Weights

### Sharpe Ratio

$$E(R_p) = w'\bar{R}$$
$$Var(R_p) = w'V_Rw$$
$$Sh^2(f) = \bar{f}'V_f^{-1}\bar{f}$$

In [11]:
def ERp(w, R):
    ER = pd.np.mean(R, axis=0)
    return w.transpose() @ ER

In [12]:
def VRp(w, R):
    CoVR = pd.np.cov(R, rowvar=False)
    return w.transpose() @ CoVR @ w

In [13]:
R = F[:"2016"][b2016].as_matrix()
CoVR = pd.np.cov(R, rowvar=False)
F[:"2016"][b2016].cov().as_matrix() == CoVR

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [14]:
def Sh2(f):
    Ef = pd.np.mean(f, axis=0)
    CoVf = pd.np.cov(f, rowvar=False)
    return Ef.transpose() @ pd.np.linalg.pinv(CoVf) @ Ef

In [15]:
def SR(w, R):
    return (ERp(w, R) / pd.np.sqrt(VRp(w, R)))

In [16]:
R = F[b2016].as_matrix()
w = pd.np.matrix([.2, .2, .2, .2, .2]).transpose()

In [17]:
w.transpose() @ pd.np.mean(R, axis=0), pd.np.mean(w.transpose() @ R.transpose())

(matrix([[ 0.4356014]]), 0.4356014015280153)

In [ ]:
w.shape, R.shape

In [18]:
ERp(w, R), VRp(w, R), SR(w, R), pd.np.sqrt(Sh2(R))

(matrix([[ 0.4356014]]),
 matrix([[ 1.23649547]]),
 matrix([[ 0.39173557]]),
 0.60064468132776772)

### Objective Function

In [19]:
def obj_SR(*args, **kwargs):
    return -SR(*args, **kwargs)

In [20]:
obj_SR(w, R)

matrix([[-0.39173557]])

In [21]:
# equality constraint functions are set to 0
cons = ({"type": "eq", "fun": lambda w: pd.np.sum(w) - 1},)

In [22]:
R = F[:"2016"][b2016].as_matrix()
res = minimize(obj_SR, [.2,.2,.2,.2,.2], args=(R,), constraints=cons)
B2016 = pd.Series(res["x"] @ R.transpose(), index=F.index)
b2016, res["x"].round(2)

(['rm', 'smb', 'HMLm', 'wml', 'RMWc'],
 array([ 0.11,  0.08,  0.23,  0.13,  0.45]))

In [35]:
R = F[:"2016"][b2016+["STR",]].as_matrix()
res = minimize(obj_SR, [.1,.1,.1,.1,.1,.5], args=(R,), constraints=cons)
B2016b = pd.Series(res["x"] @ R.transpose(), index=F.index)
b2016+["STR",], res["x"].round(2)

(['rm', 'smb', 'HMLm', 'wml', 'RMWc', 'STR'],
 array([ 0.09,  0.07,  0.22,  0.13,  0.43,  0.05]))

In [27]:
R = F[:"2016"][ff2015].as_matrix()
res = minimize(obj_SR, [.2,.2,.2,.2,.2], args=(R,), constraints=cons)
FF2015 = pd.Series(res["x"] @ R.transpose(), index=F.index)
ff2015, res["x"].round(2)

(['rm', 'smb', 'hmlo', 'rmw', 'cma'],
 array([ 0.16,  0.13,  0.01,  0.3 ,  0.4 ]))

In [28]:
R = F[:"2016"][ff2016].as_matrix()
res = minimize(obj_SR, [.2,.2,.2,.2,.2], args=(R,), constraints=cons)
FF2016 = pd.Series(res["x"] @ R.transpose(), index=F.index)
ff2016, res["x"].round(2)

(['rm', 'smb', 'hml', 'RMWc', 'cma'],
 array([ 0.12,  0.09,  0.15,  0.54,  0.11]))

In [29]:
R = F[:"2016"][ff2016b].as_matrix()
res = minimize(obj_SR, [.2,.2,.2,.2,.2], args=(R,), constraints=cons)
FF2016b = pd.Series(res["x"] @ R.transpose(), index=F.index)
ff2016b, res["x"].round(2)

(['rm', 'smb', 'hml', 'RMWr', 'cma'],
 array([ 0.1 ,  0.07,  0.12,  0.45,  0.26]))

In [36]:
models = pd.DataFrame(
    {"B2016": B2016,
     "B2016B": B2016b,
     "FF2015": FF2015,
     "FF2016": FF2016,
     "FF2016b": FF2016b,
     "Rm": F["rm"]}
)

## Table 1

In [37]:
tbl = pd.concat({"Mean":  models.mean(),
                 "Stdev": models.std(),
                 "N":     models.count()}, axis="columns")

tbl["t-stat"] = tbl["Mean"] / (tbl["Stdev"] / pd.np.sqrt(tbl["N"]))
tbl["Sh"] = tbl["Mean"] / tbl["Stdev"]
round(tbl.drop("N", axis=1).transpose(), 2)

B2016  B2016B  FF2015  FF2016  FF2016b    Rm
Mean     0.42    0.42    0.31    0.37     0.33  0.51
Stdev    0.69    0.69    0.98    0.75     0.78  4.42
t-stat  15.22   15.53    8.10   12.68    10.90  2.92
Sh       0.60    0.61    0.32    0.50     0.43  0.12

In [38]:
(models / 100 + 1).cumprod().plot()

In [ ]:
(models[:"1999"] / 100 + 1).cumprod().plot()

In [ ]:
(models["2000":] / 100 + 1).cumprod().plot()

In [ ]:
(models["1963":"1969"] / 100 + 1).cumprod().plot()

In [ ]:
(models["1970":"1979"] / 100 + 1).cumprod().plot()

In [ ]:
(models["1980":"1989"] / 100 + 1).cumprod().plot()

In [ ]:
(models["1990":"1999"] / 100 + 1).cumprod().plot()

In [ ]:
(models["2000":"2009"] / 100 + 1).cumprod().plot()

In [ ]:
(models["2010":"2016"] / 100 + 1).cumprod().plot()

In [ ]:
R = F["1996":"2016"][bs2015].as_matrix()
res = minimize(obj_SR, [.2,.2,.2,.2,.2], args=(R,), constraints=cons)
BS2015 = pd.Series(res["x"] @ R.transpose(), index=F["1996":"2016"].index)
bs2015, res["x"].round(2)

In [ ]:
R = F["1996":"2016"][ff2015].as_matrix()
res = minimize(obj_SR, [.2,.2,.2,.2,.2], args=(R,), constraints=cons)
FF2015 = pd.Series(res["x"] @ R.transpose(), index=F["1996":"2016"].index)
ff2015, res["x"].round(2)

In [ ]:
R = F["1996":"2016"][ff2016a].as_matrix()
res = minimize(obj_SR, [.2,.2,.2,.2,.2], args=(R,), constraints=cons)
FF2016a = pd.Series(res["x"] @ R.transpose(), index=F["1996":"2016"].index)
ff2016a, res["x"].round(2)

In [ ]:
R = F["1996":"2016"][ff2016b].as_matrix()
res = minimize(obj_SR, [.2,.2,.2,.2,.2], args=(R,), constraints=cons)
FF2016b = pd.Series(res["x"] @ R.transpose(), index=F["1996":"2016"].index)
ff2016b, res["x"].round(2)

In [ ]:
models = pd.DataFrame(
    {"BS2015": BS2015,
     "FF2015": FF2015,
     "FF2016a": FF2016a,
     "FF2016b": FF2016b,
     "Rm": F["1996":"2016"]["rm"]}
)

In [ ]:
(models / 100 + 1).cumprod().plot()

## Spanning Regressions

### FF2016 Operating Profit

$R^M + SMB + HML + RMW^r + CMA$

In [ ]:
factors = ff2016a
end = "2015"
contrib = []

for LHS in factors:
    RHS = [RHS for RHS in factors if RHS!=LHS]
    model = sm.OLS(F[:end][LHS], sm.add_constant(F[:end][RHS]))
    fit = model.fit()

    contrib.append(pd.Series({"name": LHS,
                    "a": fit.params["const"],
                    "Stdev": fit.resid.std(),
                    "contrib": fit.params["const"]/fit.resid.std()}))

pd.DataFrame(contrib).set_index("name")[["a", "Stdev", "contrib"]].transpose().round(3)

### FF2016b Cash Profit

$R^M + SMB + HML + RMW^c + CMA$

In [ ]:
factors = ff2016b  #  + ["wml",]
end = "2016"
contrib = []

for LHS in factors:
    RHS = [RHS for RHS in factors if RHS!=LHS]
    model = sm.OLS(F[:end][LHS], sm.add_constant(F[:end][RHS]))
    fit = model.fit()

    contrib.append(pd.Series({"name": LHS,
                    "a": fit.params["const"],
                    "SD": fit.resid.std(),
                    "N": len(fit.resid)}))

contrib = pd.DataFrame(contrib).set_index("name")  #[["a", "Stdev", "contrib", "contrib2"]].transpose().round(2)
contrib["SE"] = contrib["SD"] / contrib["N"]**(1/2)
contrib["a/SE"] = contrib["a"] / contrib["SE"]  # From table description
contrib["a/SD"] = contrib["a"] / contrib["SD"]  # From text description (sec 1)
contrib["(a/SE)^2"] = contrib["a/SE"]**2
contrib["(a/SD)^2"] = contrib["a/SD"]**2
contrib[["a", "SD", "(a/SE)^2", "(a/SD)^2"]].transpose().round(3)

### BS2015

$R^M + SMB + HML^m + RMW^c + WML$

In [ ]:
factors = bs2015  #  + ["cma",]
end = "2016"
contrib = []

for LHS in factors:
    RHS = [RHS for RHS in factors if RHS!=LHS]
    model = sm.OLS(F[:end][LHS], sm.add_constant(F[:end][RHS]))
    fit = model.fit()

    contrib.append(pd.Series({"name": LHS,
                    "a": fit.params["const"],
                    "SD": fit.resid.std(),
                    "N": len(fit.resid)}))

contrib = pd.DataFrame(contrib).set_index("name")  #[["a", "Stdev", "contrib", "contrib2"]].transpose().round(2)
contrib["SE"] = contrib["SD"] / contrib["N"]**(1/2)
contrib["a/SE"] = contrib["a"] / contrib["SE"]  # From table description
contrib["a/SD"] = contrib["a"] / contrib["SD"]  # From text description (sec 1)
contrib["(a/SE)^2"] = contrib["a/SE"]**2
contrib["(a/SD)^2"] = contrib["a/SD"]**2
contrib[["a", "SD", "(a/SE)^2", "(a/SD)^2"]].transpose().round(3)

In [ ]:
LHS = "cma"
RHS = bs2015

model = sm.OLS(F[:end][LHS], sm.add_constant(F[:end][RHS]))
fit = model.fit()
pd.Series({"name": LHS,
 "a": fit.params["const"],
 "Stdev": fit.resid.std(),
 "contrib": (fit.params["const"]/fit.resid.std())**2})

## Cumulative Returns

### Whole Sample

### 2000-